<?php

namespace Fruitcake\ImageVariants\Console;

use Carbon\CarbonImmutable;
use FilesystemIterator;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Number;
use Illuminate\Support\Str;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;
use Symfony\Component\Finder\Finder;

/**
 * Deletes generated variants that have not been touched for a while.
 *
 * Nothing here is ever irreplaceable: a deleted variant is regenerated by the
 * next request for it, at the cost of one slow response. Sources are never
 * touched — only files below the configured cache directory.
 */
class CleanupCommand extends Command
{
    /** @var string */
    protected $signature = 'image-variants:cleanup
        {--days= : Delete variants older than this many days (defaults to image-variants.cleanup.days)}
        {--accessed : Age files by when they were last read instead of when they were written}
        {--dry-run : List what would be deleted without deleting anything}';

    /** @var string */
    protected $description = 'Delete generated image variants older than the configured age';

    public function handle(): int
    {
        $days = $this->days();

        if ($days === null) {
            return self::FAILURE;
        }

        $cache = rtrim((string) config('image-variants.cache'), '/');

        if ($cache === '' || ! File::isDirectory($cache)) {
            $this->components->warn("The variant cache directory [{$cache}] does not exist; nothing to clean up.");

            return self::SUCCESS;
        }

        $accessed = (bool) $this->option('accessed');
        $dryRun = (bool) $this->option('dry-run');

        // Fractional days are allowed so a cache can be swept more than daily.
        $cutoff = CarbonImmutable::now()->subSeconds((int) round($days * 86400));

        $this->components->info(sprintf(
            '%s variants in [%s] last %s before %s.',
            $dryRun ? 'Would delete' : 'Deleting',
            $cache,
            $accessed ? 'read' : 'written',
            $cutoff->toDateTimeString(),
        ));

        [$deleted, $bytes] = $this->sweep($cache, $cutoff->getTimestamp(), $accessed, $dryRun);

        if (! $dryRun) {
            $this->pruneEmptyDirectories($cache);
        }

        $this->components->info(sprintf(
            '%s %d %s (%s).',
            $dryRun ? 'Would delete' : 'Deleted',
            $deleted,
            Str::plural('variant', $deleted),
            Number::fileSize($bytes, precision: 1),
        ));

        return self::SUCCESS;
    }

    /**
     * Delete every file below $cache last touched before $cutoff.
     *
     * @return array{int, int} The number of files removed and the bytes they took up.
     */
    protected function sweep(string $cache, int $cutoff, bool $accessed, bool $dryRun): array
    {
        $deleted = 0;
        $bytes = 0;

        foreach (Finder::create()->files()->in($cache)->ignoreDotFiles(false) as $file) {
            $path = $file->getPathname();

            // Stat by path rather than through the iterator's cached SplFileInfo:
            // a sweep can run for a while, and a file listed a moment ago may be
            // gone by now. Silenced so that a vanished file is skipped rather
            // than ending the run.
            $age = $accessed ? @fileatime($path) : @filemtime($path);

            if ($age === false || $age >= $cutoff) {
                continue;
            }

            $size = @filesize($path);

            if (! $dryRun && ! File::delete($path)) {
                $this->components->warn("Could not delete [{$path}].");

                continue;
            }

            if ($this->output->isVerbose()) {
                $this->components->twoColumnDetail(
                    $this->relative($cache, $path),
                    CarbonImmutable::createFromTimestamp($age)->diffForHumans(),
                );
            }

            $deleted++;
            $bytes += $size === false ? 0 : $size;
        }

        return [$deleted, $bytes];
    }

    /**
     * Remove the directories the sweep emptied, deepest first, leaving the cache
     * root itself in place.
     */
    protected function pruneEmptyDirectories(string $cache): void
    {
        $directories = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($cache, FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST
        );

        foreach ($directories as $directory) {
            if (! $directory instanceof SplFileInfo || ! $directory->isDir()) {
                continue;
            }

            // Checked rather than counted: the iterator caches its listing, so a
            // directory emptied a moment ago can still look occupied.
            if (! (new FilesystemIterator($directory->getPathname()))->valid()) {
                @rmdir($directory->getPathname());
            }
        }
    }

    /**
     * The age threshold in days, or null if the given one makes no sense.
     */
    protected function days(): ?float
    {
        $days = $this->option('days') ?? config('image-variants.cleanup.days', 30);

        if (! is_numeric($days) || (float) $days < 0) {
            $this->components->error('The [--days] option must be a positive number.');

            return null;
        }

        return (float) $days;
    }

    protected function relative(string $cache, string $path): string
    {
        return ltrim(str_replace($cache, '', $path), DIRECTORY_SEPARATOR);
    }
}
